# **IGNORAR LO DE ABAJO**

In [3]:
# I G N O R A R. Esto solo era de testeo
import csv

def DictionaryToMatrix(Dict: dict):
  row = []
  col = []
  #matrix = np.zeros()
  for estacion, paradas in Dict.items():
    row.append(estacion)
    for parada in paradas:
      repetido = False
      for i in col:
        if (i == parada):
          repetido = True
      if (repetido == False):
        col.append(parada)
  row_n = len(row) #+ 1
  col_n = len(col) #+ 1
  matrix = np.zeros((row_n, col_n))
  i = 0
  j = 0
  for estacion, paradas in Dict.items():
    #matrix[i + 1, 0] = row [i]
    j = 0
    for c in col:
      #matrix[0, j + 1] = col [j]
      for parada in paradas:
        if (c == parada):
          matrix[i, j] = 1
      else:
        j = j + 1

    i = i + 1
  #print(row)
  #print(col)
  #print(matrix)
  return matrix




matrix = DictionaryToMatrix(Estaciones_Buses)
print(matrix)
MatrixToCSV(matrix)

[[1. 1. 1. 0.]
 [0. 1. 1. 1.]
 [1. 1. 0. 1.]
 [1. 0. 1. 1.]]
     0    1    2    3
0  1.0  1.0  1.0  0.0
1  0.0  1.0  1.0  1.0
2  1.0  1.0  0.0  1.0
3  1.0  0.0  1.0  1.0


# **IGNORAR LO DE ARRIBA**

In [10]:
# Importamos lo necesario para generar las listas
import json
import pandas as pd
import numpy as np
import random
from os.path import exists

In [5]:
#Aquí estarán los diccionarios
#Este es de prueba, era para ver como funcionaban los diccionarios.
Estaciones_Buses = {
    '1': ['1', '2', '3'],
    '2': ['2', '3', '4'],
    '3': ['1', '2', '4'],
    '4': ['1', '3', '4'],
}
#Estaciones numeradas del 1 al 4 (por ahora)
Estaciones = {}
#Expresos numerados del 1 al 4 (por ahora)
Buses = {}

In [28]:
#Definimos una función que convierte una matriz a CSV (guardar la información)
def MatrixToCSV(matrix):
  #convertimos la matriz a tabla
  tabla = pd.DataFrame(matrix)
  #mostramos la tabla (no necesario)
  #print(tabla)
  #convertimos la tabla en un csv, no se puede hacer directamente desde la matriz
  tabla.to_csv('Estaciones_Buses.csv', index=False)

#Crea los valores aleatoreos
def randomMatrix(nrow: int, ncol: int):
  #matriz vacía
  matrix = np.zeros((nrow, ncol))
  #los índices
  i = 0
  j = 0
  #checkeamos el elemento de las filas
  while i < nrow:
    #reseteamos el contador de columnas
    j = 0
    #checkeamos el elemento de las columnas
    while j < ncol:
      #generamos un valor aleatoreo entre o y 1. Lo asignamos a la matriz
      n = random.randint(0,1)
      matrix[i,j] = n
      #avanzamos a la siguiente columna
      j = j + 1
    #avanzamos a la siguiente fila
    i = i + 1
  #convertimos la matriz a un CSV, para no tener que hacer esto cada vez que iniciamos el programa
  MatrixToCSV(matrix)
  return matrix

#lee el archivo
def readCSV():
  #verificamos si el archivo ya ha sido creado de antemano
  if exists('Estaciones_Buses.csv'):
    #leemos el archivo y lo convertimos a matriz
    matrix = np.loadtxt(open("Estaciones_Buses.csv", "rb"), delimiter=",", skiprows=1)
    return matrix
  #creamos el archivo en caso contrario
  else:
    return randomMatrix(4, 4)

#obtenemos las estaciones
def getEstaciones(matrix, nrow: int, ncol: int):
  #label de la estación
  label = ''
  #buses que pasan
  arr = []
  i = 0
  j = 0
  #verificamos filas
  while i < nrow:
    j = 0
    #el label de estación de esta fila es número "i + 1"
    label = f'{i + 1}'
    #reiniciamos en blanco los buses que llegan
    arr = []
    #verificamos columnas
    while j < ncol:
      #si el valor en tal columna y fila es uno (verdadero), implica que ese es un bus que llega
      if matrix[i][j] == 1:
        #añadimos el bus a la estación
        arr.append(f'{j + 1}')
      #avanzamos en columnas
      j = j + 1
    #avanzamos en filas
    i = i + 1
    Estaciones[label] = arr
  #print(Estaciones)

#obtenemos las estaciones
def getBuses(matrix, nrow: int, ncol: int):
  #label del buss
  label = ''
  #estaciones de llegada
  arr = []
  i = 0
  j = 0
  #verificamos columnas
  while j < ncol:
    i = 0
    #el label del bus de esta columna es expreso número "j + 1"
    label = f'{j + 1}'
    #reiniciamos en blanco las estaciones de destino
    arr = []
    #verificamos filas
    while i < nrow:
      #si el valor en tal fila y columna es uno (verdadero), implica que esa es una parada
      if matrix[i][j] == 1:
        #añadimos la parada al bus
        arr.append(f'{i + 1}')
      #avanzamos en filas
      i = i + 1
    #avanzamos en columnas
    j = j + 1
    Buses[label] = arr
  #print(Buses)

getEstaciones(readCSV(), 4, 4)
getBuses(readCSV(), 4, 4)

{'1': ['4'], '2': ['1', '2', '3'], '3': ['2', '3'], '4': ['3', '4']}
{'1': ['2'], '2': ['2', '3'], '3': ['2', '3', '4'], '4': ['1', '4']}
